### PR TITLE
chore: colors config, layout and font

### PR DESCRIPTION
**Pull request by santhitak**

### CODE REVIEW

**Review by pp3times — CHANGES_REQUESTED** [review]
Can we use font from the css file please

and if you want to make an start up file maybe you should add some dynamic opengraph too for the best for us.

But the overall look nice 👍

**Comment by santhitak** [comment]
did you mean .woff font types? and can you explain more about start-up file, maybe that's not necessary if you wanted them to learn.

**Comment by pp3times** [comment]
- start-up file : it mean starter file for team
- just move all of imported font to css file

**Comment by santhitak** [comment]
> Member
requested changes are fulfilled

**Review by pp3times — APPROVED** [review]

**Pull request merged**
